name: Run AobscanFast Benchmark

on:
  push: 
    branches: [ "NativeC" ]
  tags:
    - 'run_bench*'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore deps
        run: dotnet restore

      - name: Run configure
        run: cd AobscanFast.NativeC && ./configure.py -build -multithreaded

      - name: Run Benchmark
        run: cd .. && dotnet run -C Release --project AobscanFast.Benchmarks
  
